# Generated by Django 4.2.23 on 2025-07-29 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captcha', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaptchaLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=45)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='pageview',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Visualização de Página', 'verbose_name_plural': 'Visualizações de Página'},
        ),
        migrations.AlterField(
            model_name='pageview',
            name='referrer',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
    ]
