# Generated by Django 4.2.23 on 2025-06-10 23:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(help_text='Uma versão curta e legível do título para URLs.', max_length=200, unique=True)),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Publicação')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='blog_covers/', verbose_name='Imagem de Capa')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-published_date'],
            },
        ),
    ]
