# Generated by Django 4.2.23 on 2025-06-11 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_html',
            field=models.TextField(default='tes', editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='content_markdown',
            field=models.TextField(default='tes', verbose_name='Conteúdo em Markdown'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='subtitle',
            field=models.CharField(default='tes', max_length=200, verbose_name='Subtítulo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(verbose_name='Conteúdo (HTML ou Markdown)'),
        ),
    ]
