# Generated by Django 4.2.23 on 2025-06-11 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_content_html_post_content_markdown_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.AlterField(
            model_name='post',
            name='content_html',
            field=models.TextField(editable=False, verbose_name='Conteúdo em HTML'),
        ),
    ]
