# Generated by Django 5.2.1 on 2025-05-20 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('conteudo', models.TextField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='blog_imagens/')),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('empresa', models.CharField(blank=True, max_length=100)),
                ('periodo', models.CharField(blank=True, max_length=100)),
                ('descricao', models.TextField()),
                ('tecnologias', models.CharField(max_length=300)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='experiencias/')),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
