# Generated by Django 4.2.23 on 2025-06-10 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_apresentacao_formacao_skill_sobremim_tecnologia_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
