# Generated by Django 4.2.23 on 2025-06-11 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_delete_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='sobremim',
            name='titulo',
            field=models.CharField(default='Título Padrão', max_length=200),
            preserve_default=False,
        ),
    ]
