# Generated by Django 4.2.23 on 2025-07-29 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_sobremim_titulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='Contagem')),
            ],
            options={
                'verbose_name': 'Contagem de Visitante',
                'verbose_name_plural': 'Contagens de Visitantes',
            },
        ),
        migrations.RemoveField(
            model_name='experience',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='nivel',
        ),
        migrations.RemoveField(
            model_name='sobremim',
            name='sobre',
        ),
        migrations.RemoveField(
            model_name='sobremim',
            name='titulo',
        ),
        migrations.AddField(
            model_name='experience',
            name='descricao_html',
            field=models.TextField(blank=True, editable=False, verbose_name='Descrição (HTML)'),
        ),
        migrations.AddField(
            model_name='experience',
            name='descricao_md',
            field=models.TextField(blank=True, verbose_name='Descrição (Markdown)'),
        ),
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('backend', 'Backend Development'), ('frontend', 'Frontend Development'), ('database_tools', 'Database & Tools'), ('ai_other', 'AI & Other Skills')], default='backend', max_length=50, verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='sobremim',
            name='conteudo_html',
            field=models.TextField(blank=True, editable=False, verbose_name='Conteúdo (HTML)'),
        ),
        migrations.AddField(
            model_name='sobremim',
            name='conteudo_md',
            field=models.TextField(default='1', verbose_name='Conteúdo (Markdown)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='skill',
            name='imagem',
            field=models.ImageField(default='1', upload_to='skills/'),
            preserve_default=False,
        ),
    ]
